### ISSUE TITLE
Release v1.0.106 bumped MSRV in a patch release 

### ISSUE THREAD

**Issue by tnull** [rust-lang/cc-rs#1144]
It seems the just-released v1.0.106 bumped the MSRV from 1.63 to 1.67 in a patch release.

Unfortunately this breaks our downstream MSRV builds, which depend on rustc 1.63 (currently shipped with Debian Bookworm).

I want to ask you to consider reverting the MSRV bump as it introduces issues for users downstream that need to support 'older' Rust version, especially since raising the MSRV seems to have happened only for a mere convenience feature in https://github.com/rust-lang/cc-rs/pull/1137

**Comment by NobodyXu** [comment]
Hello, sorry to hear that it breaks your build.

Is it possible for you to pin the cc version via `Cargo.lock`?

BTW cargo is working on a msrv-aware resolution feature to help this.

**Comment by ChrisDenton** [comment]
I don't think it's currently tenable for us to consistently maintain a 3+ year MSRV.

If using the Debian system rustc is absolutely necessary, note that they do also maintain a cc-rs package for this purpose.

**Comment by NobodyXu** [comment]
> There's also the issue of -Zbuild-std, which doesn't support Cargo.lock

stdlib/rustc doesn't pin the version?

I was under the impression that stdlib/rustc pin to a specific cc version...

But if you are using `-Zbuild-version`, then it should be nightly compiler, unless you compiled the rustc with some special options to enable nightly options

**Comment by NobodyXu** [comment]
If it is for x-lto, is there another way?

I.e. compile in docker, where the rustc 1.67 and clang uses the same LLVM version?

**Comment by ChrisDenton** [comment]
> change the minor (or major) version when that point is reached

Others have tried this approach (treating it as a semver breaking change) but found it isn't really tenable. E.g. see the discussion on the API guidelines repo https://github.com/rust-lang/api-guidelines/discussions/231#discussioncomment-5864561

**Comment by NobodyXu** [comment]
I'm ok with a 1.1.0 release, that sounds very reasonable

**Comment by Nilstrieb** [comment]
How does updating it in a minor release vs a patch release help you? I don't see a significant difference there.

**Comment by NobodyXu** [comment]
A cyclical compilation error is found in #1146 , we would need to bump msrv to 1.70 to use [`std::sync::OnceLock`](https://doc.rust-lang.org/std/sync/struct.OnceLock.html#) to fix it.

**Comment by workingjubilee** [comment]
> Its not a huge difference, no, either way we're stuck pinning cc in Cargo.toml explicitly which sucks, the only difference is assuming cc takes a stance like tokio where it can/does backport security and important bugfixes (or, for cc, possibly even new platform support where it doesn't require breaking MSRV for existing platforms) to the prior minor version.

I don't think that's happening. aiui tokio has professional support explicitly paid to work on tokio and adjacent problems.

**Comment by NobodyXu** [comment]
BTW, it looks like we will have to refrain MSRV bump until next debian stable release, which is probably going to happen in 2025 Aug-Oct with rust 1.79

Finger crossed it will come soonner
